In [9]:
import lda
import lda.datasets
import numpy as np

In [2]:
X = lda.datasets.load_reuters()
vocab = lda.datasets.load_reuters_vocab()
titles = lda.datasets.load_reuters_titles()
X.shape

(395L, 4258L)

In [5]:
model = lda.LDA(n_topics=20, n_iter=500, random_state=1)
model.fit(X)
topic_word = model.topic_word_

In [73]:
n_top_words = 10
for i, topic_dist in enumerate(topic_word):
    topic_words = np.array(vocab)[np.argsort(topic_dist)][:-n_top_words:-1]
    print('Topic {}: {}'.format(i, ' '.join(topic_words)))

Topic 0: government british minister west group letters party former million
Topic 1: church first during people political country ceremony visit government
Topic 2: elvis king wright fans presley concert life death first
Topic 3: yeltsin russian russia president kremlin michael romania orthodox operation
Topic 4: pope vatican paul surgery pontiff john hospital trip rome
Topic 5: family police miami versace cunanan funeral home church kennedy
Topic 6: south simpson born york white north african black wife
Topic 7: order church mother successor since election religious head nuns
Topic 8: charles prince diana royal queen king parker bowles camilla
Topic 9: film france french against actor paris bardot magazine poster
Topic 10: germany german war nazi christian letter book scientology jews
Topic 11: east prize peace timor quebec belo indonesia nobel award
Topic 12: n't told life people church show very public come
Topic 13: years world time year last say three later news
Topic 14: mother 

In [11]:
doc_topic = model.doc_topic_
for i in range(10):
    print("{} (top topic: {})".format(titles[i], doc_topic[i].argmax()))

0 UK: Prince Charles spearheads British royal revolution. LONDON 1996-08-20 (top topic: 8)
1 GERMANY: Historic Dresden church rising from WW2 ashes. DRESDEN, Germany 1996-08-21 (top topic: 1)
2 INDIA: Mother Teresa's condition said still unstable. CALCUTTA 1996-08-23 (top topic: 14)
3 UK: Palace warns British weekly over Charles pictures. LONDON 1996-08-25 (top topic: 8)
4 INDIA: Mother Teresa, slightly stronger, blesses nuns. CALCUTTA 1996-08-25 (top topic: 14)
5 INDIA: Mother Teresa's condition unchanged, thousands pray. CALCUTTA 1996-08-25 (top topic: 14)
6 INDIA: Mother Teresa shows signs of strength, blesses nuns. CALCUTTA 1996-08-26 (top topic: 14)
7 INDIA: Mother Teresa's condition improves, many pray. CALCUTTA, India 1996-08-25 (top topic: 14)
8 INDIA: Mother Teresa improves, nuns pray for "miracle". CALCUTTA 1996-08-26 (top topic: 14)
9 UK: Charles under fire over prospect of Queen Camilla. LONDON 1996-08-26 (top topic: 8)


In [12]:
doc_topic[0]

array([  1.34782609e-02,   7.86956522e-02,   4.34782609e-04,
         4.82608696e-02,   4.34782609e-04,   4.78260870e-03,
         2.65217391e-02,   3.08695652e-02,   4.83043478e-01,
         4.78260870e-03,   4.34782609e-04,   2.21739130e-02,
         8.30434783e-02,   1.65652174e-01,   4.34782609e-04,
         4.34782609e-04,   4.34782609e-04,   1.34782609e-02,
         4.34782609e-04,   2.21739130e-02])

In [16]:
print reduce(lambda x, y: x + y, doc_topic[0])

1.0


In [19]:
X

array([[1, 0, 1, ..., 0, 0, 0],
       [7, 0, 2, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0]])

In [20]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import nltk
import time
from nltk.corpus import wordnet as wn

%matplotlib inline
plt.style.use('ggplot')

In [21]:
features_df = pd.read_table('C:\Users\JareD\Major Project\EvenSem\Data\DataSet_Feature_Extraction_2.tsv')

In [22]:
sentences = features_df[features_df['Type'] == 'train']['Sentence']

In [24]:
len(sentences)

8666

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

In [40]:
vectorizer = CountVectorizer(min_df=1, max_features=500, analyzer='word')

In [41]:
X = vectorizer.fit_transform(sentences)

In [42]:
len(vectorizer.get_feature_names())

500

In [43]:
vectorizer.get_feature_names()

[u'10',
 u'100',
 u'11',
 u'12',
 u'15',
 u'18',
 u'20',
 u'2000',
 u'2004',
 u'2005',
 u'2006',
 u'2007',
 u'2008',
 u'2009',
 u'2010',
 u'2011',
 u'2012',
 u'2013',
 u'20th',
 u'30',
 u'50',
 u'about',
 u'according',
 u'across',
 u'act',
 u'addition',
 u'africa',
 u'after',
 u'against',
 u'age',
 u'air',
 u'album',
 u'all',
 u'along',
 u'also',
 u'although',
 u'america',
 u'american',
 u'among',
 u'an',
 u'ancient',
 u'and',
 u'another',
 u'any',
 u'approximately',
 u'april',
 u'are',
 u'area',
 u'areas',
 u'army',
 u'around',
 u'as',
 u'asia',
 u'at',
 u'august',
 u'australia',
 u'available',
 u'award',
 u'awards',
 u'based',
 u'basis',
 u'battle',
 u'bc',
 u'be',
 u'became',
 u'because',
 u'become',
 u'been',
 u'before',
 u'began',
 u'being',
 u'best',
 u'between',
 u'bill',
 u'billion',
 u'black',
 u'body',
 u'book',
 u'books',
 u'born',
 u'both',
 u'bowl',
 u'british',
 u'business',
 u'but',
 u'by',
 u'california',
 u'called',
 u'can',
 u'canada',
 u'capital',
 u'card',
 u'care',

In [44]:
from sklearn.metrics.pairwise import cosine_similarity

In [51]:
(cosine_similarity(np.array([1, 0, -1]).reshape(1, -1), np.array([-1,-1, 0]).reshape(1, -1)))

array([[-0.5]])

In [52]:
vectorizer2 = CountVectorizer(vocabulary = vectorizer.get_feature_names(), analyzer='word')

In [109]:
print vectorizer2.fit_transform(["Hello how is your life today"])

  (0, 222)	1
  (0, 251)	1
  (0, 440)	1


In [62]:
cosine_similarity(Y.reshape(1, -1), X[0].reshape(1, -1))

TypeError: reshape() takes exactly 2 arguments (3 given)

In [65]:
from sklearn.metrics.pairwise import linear_kernel
cosine_similarities = linear_kernel(Y, X).flatten()

In [69]:
set(cosine_similarities)

{0.0, 1.0, 2.0, 3.0, 4.0, 5.0}

In [87]:
topic_word.shape

(20L, 500L)

In [86]:
model = lda.LDA(n_topics=20, n_iter=500, random_state=1)
model.fit(X)
topic_word = model.topic_word_

In [194]:
import lda
import lda.datasets
import numpy as np
from sklearn.metrics.pairwise import linear_kernel
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
import math
import warnings
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import nltk
import time

#Latent Dirichlet Allocation

def buildLDA(features_df):
    #Vectorize the sentences
    sentences = features_df['Sentence']
    vectorizer = CountVectorizer(max_features=5000, analyzer='word')
    X = vectorizer.fit_transform(sentences)
    vocabulary = vectorizer.get_feature_names()
    
    #Cluster the vectors
    model = lda.LDA(n_topics = 10, n_iter = 200, random_state = 1)
    model.fit(X)
    topic_word = model.topic_word_
    doc_topic = model.doc_topic_
    return model, vocabulary

def getTopicVector(sentence, model, vectorizer):
    #model, vocabulary = buildLDA()
    #vectorizer = CountVectorizer(analyzer='word', vocabulary = vocabulary)
    #sentence = sentence.decode('utf-8','ignore').encode("utf-8")
    #print sentence
    X = vectorizer.fit_transform([sentence])
    topic_vector = model.transform(X)
    return topic_vector

#Getting average vectors
def getAverageVectors(topic_vectors):
    average_topic_vectors = {}
    for key, value in topic_vectors.iteritems():
        average_topic_vectors[key] = {}
        average_topic_vectors[key][0] = np.squeeze(np.asarray(np.matrix(topic_vectors[key][0]).sum(axis = 0)))/len(topic_vectors[key][0])
        average_topic_vectors[key][1] = np.squeeze(np.asarray(np.matrix(topic_vectors[key][1]).sum(axis = 0)))/len(topic_vectors[key][1])
        average_topic_vectors[key][0] = normalizeVector(average_topic_vectors[key][0])
        average_topic_vectors[key][1] = normalizeVector(average_topic_vectors[key][1])
        
    return average_topic_vectors

def normalizeVector(vector):
    vector_magnitude = math.sqrt(sum([x * x for x in vector]))
    vector = [x/vector_magnitude for x in vector]
    return vector

def getLDAFeature():
    #Training the model and soft clustering sentences
    features_df = pd.read_table('C:\Users\JareD\Major Project\EvenSem\Data\DataSet_Feature_Extraction_2.tsv')
    features_df_train = features_df[features_df['Type'] == 'train']
    model, vocabulary = buildLDA(features_df_train)
    vectorizer = CountVectorizer(analyzer='word', vocabulary = vocabulary)
    #x = 1
    topic_vectors = {}
    
    for question_type in features_df_train['QuestionType'].unique():
        topic_vectors[question_type] = {1 : [], 0 : []}
        df = features_df_train[features_df_train['QuestionType'] == question_type]
        df = df.head(10)
        for index, row in df.iterrows():
            topic_vector = getTopicVector(row['Sentence'], model, vectorizer)
            if row['Label'] == 1:
                topic_vectors[question_type][1].append(topic_vector[0])
            else:
                topic_vectors[question_type][0].append(topic_vector[0])
    
    
    #x = 2
    average_topic_vectors = getAverageVectors(topic_vectors)
    print average_topic_vectors
    #x = 3
    #Getting cosine similarity
    sentence = "the world is not big enough for two super villains"
    topic_vector = getTopicVector(sentence, model, vectorizer)
    topic_vector = normalizeVector(topic_vector[0])
    print topic_vector
    positive_similarity = cosine_similarity(average_topic_vectors['DESC'][1], topic_vector)
    negative_similarity = cosine_similarity(average_topic_vectors['DESC'][0], topic_vector)
    #print positive_similarity, negative_similarity
    #x = 4
    return positive_similarity, negative_similarity
    
    

positive_similarity, negative_similarity = getLDAFeature()       
print positive_similarity, negative_similarity


{'ENTY': {0: [0.61029946887328501, 0.026185157045858505, 0.73979018680290409, 0.049705206626920705, 0.070038568584980893, 0.17382139680965189, 0.14284657149944902, 0.054937669692581827, 0.10256715773403591, 0.089588929692460559], 1: [0.00081762778396759096, 0.0010788622582196521, 0.99996491560047507, 0.0031750627711143145, 0.0021213744446699216, 0.0025921675936261116, 0.004481918321645518, 0.0013021981864938447, 0.003015860050143428, 0.004019427745390213]}, 'LOC': {0: [0.1418234217053389, 0.082711314201614344, 0.098667357556026722, 0.14043445914340572, 0.32038014417898952, 0.089993130055563156, 0.069603369066054896, 0.26226197569440923, 0.86931209359330885, 0.0592973996683838], 1: []}, 'NUM': {0: [0.021681866217045032, 0.061814156636969216, 0.03097545001188334, 0.10161991882504835, 0.1719079898574675, 0.94282443542366123, 0.060725673775915985, 0.16939172879569628, 0.15813642991129767, 0.092543241770283655], 1: [0.01954633669583912, 0.050969099891904734, 0.029542782151223697, 0.02025185

In [190]:
vector = topic_vector[0]
print sum(vector)
vector_magnitude = math.sqrt(sum([x * x for x in vector]))
vector = [x/vector_magnitude for x in vector]
print sum(vector)

1.0
1.55516948961


In [ ]:
#Getting average vectors
def getAverageVectors():
    average_topic_vectors = {}
    for key, value in topic_vectors.iteritems():
        average_topic_vectors[key][0] = np.squeeze(np.asarray(np.matrix(topic_vectors[key][0]).sum(axis = 0)))/len(topic_vectors[key][0])
        average_topic_vectors[key][1] = np.squeeze(np.asarray(np.matrix(topic_vectors[key][1]).sum(axis = 0)))/len(topic_vectors[key][1])
    return average_topic_vectors



In [131]:
#verification (ignore)
sums = 0
for key, value in topic_vectors.iteritems():
    print key
    print len(value[0])
    print len(value[1])
    sums = sums + len(value[0]) + len(value[1])

print sums
print len(features_df[features_df['Type'] == 'train'].index)

ENTY
1064
154
LOC
1201
173
HUM
1312
169
NUM
2010
208
DESC
2040
335
8666
8666


In [141]:
np.squeeze(np.asarray(np.matrix(topic_vectors['DESC'][0]).sum(axis = 0)))/len(topic_vectors['DESC'][0])

array([ 0.08126983,  0.03974846,  0.06698567,  0.17432506,  0.17846414,
        0.19014801,  0.04245724,  0.07072159,  0.09212471,  0.06081411])

In [160]:
sentences = features_df[features_df['Type'] == 'train']['Sentence']
vectorizer = CountVectorizer(max_features=5000, analyzer='word')
X = vectorizer.fit_transform(sentences)
vocabulary = vectorizer.get_feature_names()

model = lda.LDA(n_topics = 10, n_iter = 500, random_state = 1)
model.fit(X)
topic_word = model.topic_word_
doc_topic = model.doc_topic_
print topic_word

[[  6.19617077e-07   6.19617077e-07   6.19617077e-07 ...,   6.19617077e-07
    6.19617077e-07   6.19617077e-07]
 [  6.43128175e-07   6.43128175e-07   6.43128175e-07 ...,   6.43128175e-07
    6.43128175e-07   6.43128175e-07]
 [  9.48071638e-04   1.80090969e-03   4.73798920e-07 ...,   4.73798920e-07
    4.73798920e-07   4.73798920e-07]
 ..., 
 [  3.36752271e-03   3.13263389e-03   7.83745694e-04 ...,   7.82962731e-07
    7.82962731e-07   4.70560601e-04]
 [  7.57059581e-07   7.57059581e-07   7.57059581e-07 ...,   7.57059581e-07
    7.57059581e-07   2.27874934e-04]
 [  6.45869664e-07   6.45869664e-07   6.45869664e-07 ...,   6.45869664e-07
    3.23580701e-04   6.45869664e-07]]


In [196]:
v = CountVectorizer(analyzer='word', vocabulary = ['green', 'red', 'blue'])
print v.fit_transform(['hello green red'])

  (0, 0)	1
  (0, 1)	1


In [201]:
20 * [0]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [206]:
[[3]][0][0]

3

In [214]:
import pickle
average_topic_vectors = pickle.load(open("C:\Users\JareD\Major Project\EvenSem\Models\LDA\Average_Topic_Vectors_2.pkl", "rb"))

In [215]:
for key, value in average_topic_vectors.iteritems():
    print key
    print "0"
    print value[0]
    print "1"
    print value[1]

LOC
0
[0.12727258866973465, 0.23355766765640823, 0.23625923624920767, 0.26466063986303645, 0.16917651146857721, 0.18573996810491286, 0.17407322238388548, 0.086128609442843312, 0.21156725514318908, 0.13625795439004004, 0.21932634475646839, 0.15152792316706304, 0.16958467834473726, 0.56564495663469283, 0.23403780981410893, 0.19158550942426197, 0.16585997595278731, 0.25922671196163943, 0.13040242003833497, 0.12748641359254029]
1
[0.1762598207871888, 0.094811090047981675, 0.082356131389920234, 0.12642704728646509, 0.040884166415926466, 0.089163481830290978, 0.071668551248603357, 0.030835361398159355, 0.39830715939718342, 0.063151422022759834, 0.086683242556200565, 0.08088204282760772, 0.12778147958954192, 0.81416773137286924, 0.17396263999076805, 0.07622233660794013, 0.096872950178936768, 0.11215419973027423, 0.067158329846123535, 0.055066821057391593]
HUM
0
[0.32055426067216602, 0.23989968536179862, 0.18597727872946082, 0.19623103939668424, 0.22639537898191017, 0.17865134950147915, 0.1817